pipeline:
  name: "vtxflow-ci"

stages:
  - build
  - test

jobs:
  # Build Stage
  - name: "build-package"
    stage: "build"
    image: "gradle:8.13-jdk21"
    script:
      - "echo 'Current directory:' && pwd"
      - "echo 'Files in current dir:' && ls -la"
      - "./gradlew build -x test"
    artifacts:
      paths:
        - "build/libs/*.jar"
      expire_in: "7 days"
    allow_failure: true

  # Test Stage
  - name: "run-tests"
    stage: "test"
    image: "gradle:8.13-jdk21"
    script:
      - "./gradlew test"
    needs:
      - "build-package"
    artifacts:
      paths:
        - "build/reports/tests"
      expire_in: "7 days"
    allow_failure: true

